# config.yaml
metadata: "metadata.tsv"

fastp:
  threads: 4
  cut_front: true
  cut_front_window_size: 1
  cut_front_mean_quality: 20
  cut_tail: true
  cut_tail_window_size: 1
  cut_tail_mean_quality: 20
  overlap_len_require: 5
  length_required: 100

bowtie2_index: "/path/to/bowtie2/index/prefix"  
gtf: "/path/to/annotation.gtf"

threads:
  align: 8
  samtools: 8
  featurecounts: 8

outdir: "results"
